# Generated by Django 4.2.5 on 2023-10-10 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_verified_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 12, 23, 13, 919098, tzinfo=datetime.timezone.utc)),
        ),
    ]
