# Generated by Django 4.2.5 on 2023-10-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uc_add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='code',
            name='code',
        ),
        migrations.AddField(
            model_name='code',
            name='key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
