# Generated by Django 4.2.5 on 2023-10-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_rechargelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
