# Generated by Django 4.2.5 on 2023-10-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
