# Generated by Django 4.2.5 on 2023-10-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_giventoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giventoken',
            name='user',
        ),
    ]
